### ISSUE TITLE
Upgrade Project to Latest Unity Version

### ISSUE THREAD

**Issue by JordanFest** [JordanFest/U_SatanicPanic#11]
Before the game gets complicated, we should upgrade to the latest Unity version.

**Comment by tinder-aaronweaver** [comment]
From my initial assessment of the game, unity hooks don't seem too large in terms of C# code, so it should be a relatively smooth transition.

I haven't RTFM'd the change logs for newer version, so take this with a grain of salt.

**Comment by JordanFest** [comment]
Even then, most of the conflicts would arise from legacy, which is planned to be cleaned out anyways. Forces the issue.

**Comment by JordanFest** [comment]
PR now up to resolve this issue
